# Generated by Django 3.2.9 on 2021-12-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='accepted_date',
            field=models.DateField(blank=True, default=False, null=True),
        ),
    ]
